


const Discord = require('discord.js');
const client = new Discord.Client();
console.log("Scrpit By Dream");


client.on("ready", () => {
let channel =     client.channels.get("506385954039267338")
setInterval(function() {
channel.send(`abcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyzabcefghijklmnopqrstuvwyz`);
}, 25)
})
 
 
client.login('NTA2Mzg1OTU0MDM5MjY3MzM4.DuQ5Nw.sLkUeErW9UUn0hFVK45dPrZzBh0');
